<template>
  <UCard variant="subtle">
    <template #header>
      <Placeholder class="h-8">
        <div class="flex justify-center text-2xl">
          <strong>DMP Human Evaluation</strong>
        </div>
      </Placeholder>
    </template>

    <Placeholder class="h-100">
      <p class="h-20">
      This research study, approved by the Institutional Review Board (IRB), is designed to evaluate
      the potential of artificial intelligence (AI) to support the development and assessment of
      high-quality, funder-compliant Data Management Plans.
    </p>

    <p class="h-10">
      As part of your participation, you will review and provide structured feedback on at least
      two AI-generated DMPs. You will be guided through the following pages:
    </p>

    <ul class="list-disc pl-12 space-y-4 h-65">
      <li>
        <strong>Background Information</strong><br />
        You’ll be asked to provide information about your professional role, experience with DMPs,
        and attitudes toward the use of AI in research. All questions are optional and serve to
        contextualize your feedback in alignment with IRB requirements.
      </li>

      <li>
        <strong>Structured Input for DMP Generation</strong><br />
        You’ll enter key details about a hypothetical or real research project, including data types,
        subjects involved, and the sponsoring institute. This information will be used to
        automatically generate sample DMP content.
      </li>

      <li>
        <strong>Evaluation of AI-Generated DMPs</strong><br />
        You will review and assess DMP elements generated by an AI model, using standardized criteria
        such as technical accuracy, completeness, and clarity. You may also provide qualitative
        feedback and identify any issues.
      </li>
    </ul>

    <p>
      Your participation is valuable in shaping the future of AI-assisted research infrastructure.
      All responses are confidential and used solely for research purposes in accordance with ethical
      and regulatory standards.
    </p>
    </Placeholder>

    <template #footer>
      <Placeholder class="h-8">
        <div class="flex justify-end">
          <UButton color="primary" to="background">
            Get Started
          </UButton>
        </div>
      </Placeholder>
    </template>
  </UCard>
</template>
